apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: construction-receptionist

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/hpa.yaml

namePrefix: prod-

replicas:
  - name: construction-receptionist
    count: 5

images:
  - name: buildpro.azurecr.io/construction-receptionist
    newTag: prod

patches:
  - target:
      kind: ConfigMap
      name: construction-receptionist-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: "prod"
      - op: replace
        path: /data/LOG_LEVEL
        value: "warn"
